---
description: "delay response"

request:
  method: GET
  path: /delay
response:
  statusCode: 200
  headers:
    Content-Type:
      - "application/json"
    Access-Control-Allow-Origin:
      - "*"
  body: '{"id": {{fake.Digits}},"message": "delayed response from the server","test": "additional data"}'
control:
  delay: "2s"
