---
description: "hello test"

request:
  method: GET
  path: /hello
response:
  statusCode: 200
  headers:
    Content-Type:
      - "application/json"
  body: >
    {  
      "id": {{fake.Digits}},
      "message": "hello world from the server"
    }
